spring:
  cloud:
    gateway:
      routes:
        - id: most-viewed-service
          uri: http://localhost:7887
          predicates:
           - Path=/api/v3/clubs/**
        - id: league-info-service
          uri: http://localhost:8084
          predicates:
           - Path=/api/v2/**
        - id: generate
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/**
      filters:
        - name: CustomFilter

  application:
    name: spring-cloud-gateway-service
server:
  port: 8888



management:
  endpoints:
    web:
      exposure:
        include: "*"
